import {
  GitHubClient,
  checkFileExists,
  createBranch,
  createCommitWithFiles,
  createPullRequest,
} from "@Emitkit/github";
import { generateNpmWorkflow, generatePyPIWorkflow } from "@Emitkit/generators";

function parseConfigList(val: any): string[] {
  if (!val) return [];
  if (Array.isArray(val)) return val;
  if (typeof val === "string") {
    try {
      const parsed = JSON.parse(val);
      if (Array.isArray(parsed)) return parsed;
      return [parsed];
    } catch {
      return val
        .split(/[,\s]+/)
        .map((s) => s.trim())
        .filter(Boolean);
    }
  }
  return [];
}

export async function commitOutput(
  project: any,
  config: any,
  files: Array<{ path: string; content: string }>,
  runId: string,
  version: string,
  githubClient: GitHubClient
): Promise<{ prUrl: string; branchName: string }> {
  // Determine the target output repository
  const repoFullName =
    project.outputMode === "separate"
      ? project.outputRepoFullName
      : project.repoFullName;

  if (!repoFullName) {
    throw new Error("Repository full name is required but not provided.");
  }

  const [owner, repoName] = repoFullName.split("/");
  if (!owner || !repoName) {
    throw new Error(`Invalid repository full name format: ${repoFullName}`);
  }

  // Filter out custom files if they exist in the default branch
  const filteredFiles: Array<{ path: string; content: string }> = [];
  for (const file of files) {
    if (file.path.includes("/custom/")) {
      const exists = await checkFileExists(
        githubClient,
        owner,
        repoName,
        file.path,
        project.defaultBranch
      );
      if (!exists) {
        filteredFiles.push(file);
      }
    } else {
      filteredFiles.push(file);
    }
  }

  // Parse config outputs and sdk languages
  const outputs = parseConfigList(config.outputs);
  const sdkLanguages = parseConfigList(config.sdkLanguages);

  const filesToCommit = [...filteredFiles];

  // Add GitHub Actions workflow files based on config
  if (outputs.includes("SDK")) {
    if (sdkLanguages.includes("typescript")) {
      filesToCommit.push({
        path: ".github/workflows/publish-npm.yml",
        content: generateNpmWorkflow(config.outputDir),
      });
    }
    if (sdkLanguages.includes("python")) {
      filesToCommit.push({
        path: ".github/workflows/publish-pypi.yml",
        content: generatePyPIWorkflow(config.outputDir),
      });
    }
  }

  // Fetch the latest commit SHA of project.defaultBranch
  const refResponse = await githubClient.getOctokit().git.getRef({
    owner,
    repo: repoName,
    ref: `heads/${project.defaultBranch}`,
  });
  const baseSha = refResponse.data.object.sha;

  // Create branch named emitkit/run-${runId}
  const branchName = `emitkit/run-${runId}`;
  await createBranch(githubClient, owner, repoName, branchName, baseSha);

  // Commit files
  const commitMessage = `chore: emitkit run #${runId} — ${version}`;
  await createCommitWithFiles(
    githubClient,
    owner,
    repoName,
    branchName,
    filesToCommit,
    commitMessage
  );

  // Create Pull Request
  const prTitle = `Emitkit: Generated SDK v${version}`;
  const prBody = `## Emitkit Generation Run

**Run ID:** ${runId}
**Version:** ${version}
**Outputs:** ${outputs.join(", ")}

### Generated Files
${filesToCommit.map((f) => `- ${f.path}`).join("\n")}

---
*This PR was automatically generated by Emitkit.*`;

  const prUrl = await createPullRequest(
    githubClient,
    owner,
    repoName,
    prTitle,
    prBody,
    branchName,
    project.defaultBranch
  );

  return { prUrl, branchName };
}
